# To customize messages use messages.yml file

# Set how much points player should get after mining each ore
points:
  coal: 0
  iron: 1
  copper: 1
  gold: 4
  redstone: 5
  lapis: 6
  diamond: 10
  emerald: 9